version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  # backend:
  #   build:
  #     context: ./apps/backend  # Context for backend Dockerfile
  #     dockerfile: Dockerfile
  #   container_name: nestjs-backend
  #   environment:
  #     DATABASE_URL: "postgresql://user:password@db:5432/mydb"
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - db
  #   restart: always

volumes:
  db_data:
