name: Deploy to DigitalOcean

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to your project directory
            cd backend
            
            # Execute your existing hosting script
            if [ -f "./deployment.sh" ]; then
              echo "Found deployment.sh - executing..."
              chmod +x ./hosting.sh
              ./deployment.sh
            else
              echo "ERROR: deployment.sh not found in the current directory."
              exit 1
            fi
